### ISSUE TITLE
Simulation for multiple substrates

### ISSUE THREAD

**Issue by alpha027** [kerkelae/disimpy#10]
Hi,

I want to know if it is possible to define multiple substrates in a single simulation ? ( say having multiple spheres and ellipsoids in the same simulation environment)

**Comment by kerkelae** [comment]
You can do this for intra-compartmental diffusion (i.e., inside spheres and ellipsoids) by aggregating the results from two simulations. For instance, for a combination of spheres and cylinders: `s_total = s_sphere / n_walkers * f_sphere + s_cylinder / n_walkers * f_cylinder`, where s_i are the signals and f_i the signal fractions. If you want the simulations to also include a third, "extra-cellular" compartment, this can be done by constructing a triangular mesh that contains spheres, cylinders, and space outside these compartments. Please see [this section](https://disimpy.readthedocs.io/en/latest/tutorial.html#Triangular-meshes) in the tutorial. There is a voxel that contains several spheres represented by a triangular mesh. Is this similar to what you would like to do?

**Comment by alpha027** [comment]
Thanks for your reply and sorry for the delay.
I have seen the part using triangular mesh. What I am interesting in is to simulate fibers constructed with methods like [MEDUSA](https://www.sciencedirect.com/science/article/pii/S105381191930151X) where a fiber is represented a set of overlapping spheres. What I want is to not use directly meshes. Do you think it is feasible and relatively easy to add this feature in disimpy ?

![1-s2 0-S105381191930151X-gr3](https://user-images.githubusercontent.com/27587257/143249994-26e6800b-08ec-4254-839d-0ecc6f10155a.jpg)
Fiber created with MEDUSA.

**Comment by kerkelae** [comment]
I'm not familiar with the details, but I think MEDUSA is just an algorithm for generating complex phantoms (i.e., simulated microstructures). I don't think it can generate simulated signals. You can use Disimpy to generate the diffusion-weighted MR signal from phantoms generated by MEDUSA only if you can convert them into triangular meshes first.
